import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

import AppContext from "@/components/AppContext";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="sm:max-w-7xl  mx-auto  p-4">
         <AppContext>
            <Header />
            {children}
            <footer className="border-t p-8 text-center mt-16 ">
              &copy; 2023 All RIght Reserved
            </footer>
         </AppContext>
        </main>
      </body>
    </html>
  );
}
